INSERT INTO STUDENT VALUES (1,'Jas','30');
INSERT INTO STUDENT VALUES (2,'Liz','34');
INSERT INTO STUDENT VALUES (3,'Jazz','29');
INSERT INTO STUDENT VALUES (4,'Sam','31');
INSERT INTO STUDENT VALUES (5,'Tim','32');